apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # base64 encoded values:
  # echo -n '123456' | base64 -> MTIzNDU2
  # echo -n 'root' | base64 -> cm9vdA==
  mysql-root-password: MTIzNDU2
  mysql-user: cm9vdA==